function TG = MFR_V2_GenerateTrajectoryType(TG_ID,...
        TG_R0X, TG_R0Y, TG_R0Z, ...
        TG_VX, TG_VY, TG_VZ,...
        TG_RCS)
    %Targets
    TG = struct( ...
        'ID',TG_ID, ...
        'R0',[TG_R0X TG_R0Y TG_R0Z], ...
        'V', [TG_VX TG_VY TG_VZ], ...
        'RCS',TG_RCS ...
    );
%     coder.varsize('TG.ID');
%     coder.varsize('TG.R0');
%     coder.varsize('TG.V');
%     coder.varsize('TG.RCS');
end