@startuml

title Send messages

loop for each message
    Model -> Model ++ : send(msg)
    Model -> MsgChannelCarrier ++ : get().send(id, msg)
    loop for each receiver
        MsgChannelCarrier -> Model : update queue
    end loop
    return done
    deactivate Model
end loop

@enduml